// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Support both variable names for backwards compatibility
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables - use placeholder values in development if missing
// This allows the app to start in Lovable even if Supabase isn't configured yet
const validUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const validKey = SUPABASE_ANON_KEY || 'placeholder-key';

// Log warning if environment variables are missing
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('⚠️ Supabase environment variables are missing. Please configure Supabase integration in Lovable.');
  console.warn('Missing:', !SUPABASE_URL ? 'VITE_SUPABASE_URL' : '', !SUPABASE_ANON_KEY ? 'VITE_SUPABASE_ANON_KEY' : '');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(validUrl, validKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});